name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload Apk
        uses: actions/upload-artifact@v2
        with:
          name: Unsigned Apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk